const mockAccountDetailsResponse = {
  primaryEmail: 'maplehilldiscgolf@gmail.com',
  id: 87,
  accountName: 'maple hill',
  createdAt: '2023-11-10T13:22:20.426Z',
  lastActive: '2025-04-13T16:56:58.516Z',
  since: {
    days: 740,
    hours: 10,
    minutes: 37,
    seconds: 39,
    milliseconds: 573.919,
  },
  accountPath: '/maple-hill',
  settings: {
    accountPath: '/maple-hill',
    timezone: 'CST',
    smsTemplate:
      'Your {discDescription} was returned to {businessName}, {accountAddress}.',
    businessName: 'Maple Hill Disc Golf',
    phone: '15087543472',
    state: 'Massachusetts',
    zipCode: '01524',
    city: 'Leicester',
    address: '132 Marshall Street',
    title: 'Maple Hill Found Disc List',
    accountName: 'Maple Hill',
    metaDescription:
      'This is a list of all cataloged found discs that have been returned and are at Maple Hill!',
    gracePeriodInDays: '60',
    customInstructions:
      "Discs will be held for 60 days.\nPlease check our website for shop hours and policy updates.\n\nIf you can't pick up your discs within 60 days, you can get it shipped back here! https://www.maplehilldiscgolf.com/lost-and-found",
  },
  stats: {
    discsCount: 39130,
    discsActive: 26,
    discsDeleted: 13,
    discsReturned: 20452,
    discsSold: 18639,
  },
  users: [
    {
      id: '101',
      email: 'maplehilldiscgolf@gmail.com',
      verified: true,
      lastActive: null,
      sessionStart: null,
    },
  ],
  accountActivity: {
    discsCreatedInLastMonth: 0,
    discsCreatedInLastTwoWeeks: 0,
  },
  isActive: false,
}

const mockAccountData = [
  {
    id: 87,
    accountName: 'maple hill',
    createdAt: '2023-11-10T13:22:20.426Z',
    accountPath: '/maple-hill',
  },
  {
    id: 107,
    accountName: 'bomber lost and found',
    createdAt: '2024-05-27T01:26:30.560Z',
    accountPath: '/bomber-lost-and-found',
  },
  {
    id: 75,
    accountName: 'tri-fox disc golf',
    createdAt: '2023-07-06T17:24:26.814Z',
    accountPath: '/tri-fox-disc-golf',
  },
  {
    id: 49,
    accountName: 'Madge the Horse',
    createdAt: '2022-04-09T16:33:54.609Z',
    accountPath: '/madge-the-horse',
  },
  {
    id: 127,
    accountName: 'nichols field',
    createdAt: '2024-08-20T17:16:51.036Z',
    accountPath: '/nichols-field',
  },
  {
    id: 90,
    accountName: 'bronte disc golf club',
    createdAt: '2024-03-14T12:17:11.189Z',
    accountPath: '/bronte-disc-golf-club',
  },
  {
    id: 51,
    accountName: 'Jeremy the Cheetah',
    createdAt: '2022-04-24T06:10:31.267Z',
    accountPath: '/jeremy-the-cheetah',
  },
  {
    id: 52,
    accountName: 'Charlotte the Waxwing',
    createdAt: '2022-04-24T12:21:18.924Z',
    accountPath: '/charlotte-the-waxwing',
  },
  {
    id: 53,
    accountName: 'Gordon the Mexican Lookdown',
    createdAt: '2022-04-24T14:26:29.066Z',
    accountPath: '/gordon-the-mexican-lookdown',
  },
  {
    id: 54,
    accountName: 'Alvin the Haddock',
    createdAt: '2022-04-24T14:58:35.795Z',
    accountPath: '/alvin-the-haddock',
  },
  {
    id: 55,
    accountName: 'Aaron the Fugu (also called Pufferfish)',
    createdAt: '2022-04-24T17:25:38.052Z',
    accountPath: '/aaron-the-fugu-also-called-pufferfish',
  },
  {
    id: 56,
    accountName: 'Lucile the Civet',
    createdAt: '2022-04-24T17:28:08.067Z',
    accountPath: '/lucile-the-civet',
  },
  {
    id: 57,
    accountName: 'Mabel the Banteng',
    createdAt: '2022-04-24T20:17:00.284Z',
    accountPath: '/mabel-the-banteng',
  },
]

const mockDiscData = [
  {
    id: '91664',
    firstName: 'Madison',
    lastName: 'Walker',
    phone: '',
    pdga: '59431',
    description: null,
    createdAt: '2025-03-23T19:28:03.139Z',
    accountId: '87',
    status: 'active',
    location: null,
    notes: null,
    updatedAt: '2025-11-07T08:14:03.335Z',
    brand: null,
    model: null,
    color: null,
    plastic: null,
    lastNotified: null,
    binLocation: 'Pro box',
    smsStatus: 'no-phone',
    contactStatus: null,
    contactStatusNotes: null,
    allowReminder: false,
    isPastGracePeriod: true,
    daysLeftToPickup: -182,
    days: 242,
    searchField: 'MadisonWalker59431',
  },
  {
    id: '91633',
    firstName: 'Casey',
    lastName: 'White',
    phone: '',
    pdga: null,
    description: null,
    createdAt: '2025-03-23T18:59:36.663Z',
    accountId: '87',
    status: 'active',
    location: null,
    notes: null,
    updatedAt: '2025-11-07T08:14:03.335Z',
    brand: null,
    model: 'Nordic',
    color: 'Pink',
    plastic: null,
    lastNotified: null,
    binLocation: 'Pro box',
    smsStatus: 'no-phone',
    contactStatus: null,
    contactStatusNotes: null,
    allowReminder: false,
    isPastGracePeriod: true,
    daysLeftToPickup: -182,
    days: 242,
    searchField: 'CaseyWhiteNordicPink',
  },
  {
    id: '82080',
    firstName: null,
    lastName: null,
    phone: '******8300',
    pdga: null,
    description: null,
    createdAt: '2024-11-24T16:40:24.004Z',
    accountId: '87',
    status: 'active',
    location: null,
    notes: null,
    updatedAt: '2024-11-24T16:40:29.568Z',
    brand: null,
    model: null,
    color: 'orange driver',
    plastic: null,
    lastNotified: null,
    binLocation: null,
    smsStatus: 'delivered',
    contactStatus: null,
    contactStatusNotes: null,
    allowReminder: false,
    isPastGracePeriod: true,
    daysLeftToPickup: -301,
    days: 361,
    searchField: '8300orange driver',
  },
]

export { mockAccountDetailsResponse, mockAccountData }
